name = "BLISBLAS"
uuid = "6f275bd8-fec0-4d39-945b-7e95a765fa1e"
authors = ["Carsten Bauer <mail@carstenbauer.eu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
blis_jll = "6136c539-28a5-5bf0-87cc-b183200dce32"

[compat]
blis_jll = "0.9"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
