name = "BLISBLAS"
uuid = "6f275bd8-fec0-4d39-945b-7e95a765fa1e"
authors = ["Carsten Bauer <carsten.bauer@uni-paderborn.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
