name: Run tests

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1.7, 1.8]
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # exclude:
        #   - os: macOS-latest
        #     julia-arch: x86

    steps:
      - uses: actions/checkout@v3.5.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@main
      - uses: julia-actions/julia-runtest@main
      - uses: julia-actions/julia-uploadcodecov@master
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#      - uses: julia-actions/julia-uploadcoveralls@master
#        env:
#          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
